[phases.setup]
nixPkgs = ["nodejs_20", "caddy"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "caddy file-server --root /app/dist --listen :${PORT:-4173}"
