[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[phases.caddy]
cmds = []

[start]
cmd = "caddy file-server --root /app/dist --listen :${PORT:-4173}"
